package com.estebangm.euler;

import java.util.ArrayList;
import java.util.List;

/**
 * ID 2
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 *
 * ANSWER: 4613732
 */
public class EvenFibonacciNumbers {
    public static final int FIBONACCI_NUMBER_MAX_VALUE = 4000000;

    public static void main (String [] args) {
        System.out.println(getFibonacciNumbersUntilMaxNumber());
    }

    private static int getFibonacciNumbersUntilMaxNumber() {
        int sumOfEvenFibonacciNumbersUntilMaxNumber = 0;
        int i = 1;
        int fibonacciNumber;
        while (true) {
            fibonacciNumber = getNFibonacciNumber(i);
            if (fibonacciNumber > FIBONACCI_NUMBER_MAX_VALUE) {
                break;
            }
            if (fibonacciNumber % 2 == 0) {
                sumOfEvenFibonacciNumbersUntilMaxNumber += fibonacciNumber;
            }
            i++;
        }
        return sumOfEvenFibonacciNumbersUntilMaxNumber;
    }

    private static Integer getNFibonacciNumber(int n) {
        if (n == 1) {
            return 1;
        } else if (n == 2) {
            return 2;
        } else {
            return getNFibonacciNumber(n-2) + getNFibonacciNumber(n-1);
        }
    }
}
